src/Entity/Espace.php
<?php

namespace App\Entity;

use App\Repository\EspaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EspaceRepository::class)]
class Espace
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $superficie = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_ouverture = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fermeture = null;

    #[ORM\OneToMany(mappedBy: 'espace_id', targetEntity: Enclos::class, orphanRemoval: true)]
    private Collection $enclos;

    public function __construct()
    {
        $this->enclos = new ArrayCollection();
    }

    public function __toString() :string {
        return $this->nom;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getSuperficie(): ?int
    {
        return $this->superficie;
    }

    public function setSuperficie(int $superficie): self
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getDateOuverture(): ?\DateTimeInterface
    {
        return $this->date_ouverture;
    }

    public function setDateOuverture(?\DateTimeInterface $date_ouverture): self
    {
        $this->date_ouverture = $date_ouverture;

        return $this;
    }

    public function getDateFermeture(): ?\DateTimeInterface
    {
        return $this->date_fermeture;
    }

    public function setDateFermeture(?\DateTimeInterface $date_fermeture): self
    {
        $this->date_fermeture = $date_fermeture;

        return $this;
    }

    /**
     * @return Collection<int, Enclos>
     */
    public function getEnclos(): Collection
    {
        return $this->enclos;
    }

    public function addEnclo(Enclos $enclo): self
    {
        if (!$this->enclos->contains($enclo)) {
            $this->enclos->add($enclo);
            $enclo->setEspaceId($this);
        }

        return $this;
    }

    public function removeEnclo(Enclos $enclo): self
    {
        if ($this->enclos->removeElement($enclo)) {
            // set the owning side to null (unless already changed)
            if ($enclo->getEspaceId() === $this) {
                $enclo->setEspaceId(null);
            }
        }

        return $this;
    }
}

src/Form/EspaceType.php
<?php

namespace App\Form;

use App\Entity\Espace;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EspaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('superficie')
            ->add('date_ouverture')
            ->add('date_fermeture')
            ->add("OK", SubmitType::class, ["label" => "Ajouter"])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Espace::class,
        ]);
    }
}

src/Controller/EspacesController.php
<?php

namespace App\Controller;

use App\Entity\Espace;
use App\Form\EspaceSupprimerType;
use App\Form\EspaceType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function PHPUnit\Framework\throwException;

class EspacesController extends AbstractController
{
    #[Route('/', name: 'app_espaces')]
    public function index(ManagerRegistry $doctrine, Request $request): Response
    {

        $espace = new Espace();
        $form = $this->createForm(EspaceType::class, $espace);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ((($form->getData()->getDateOuverture() !== null && $form->getData()->getDateFermeture() !== null) && $form->getData()->getDateOuverture() < $form->getData()->getDateFermeture())
                || ($form->getData()->getDateOuverture() === null && $form->getData()->getDateFermeture() === null)
            ) {
                $em = $doctrine->getManager();

                $em->persist($espace);

                $em->flush();
            } else {
                throw $this->createNotFoundException("Erreur dans le formulaire : vérifier si les dates d'ouverture et de fermeture sont correctement indiquées");
            }
        }

        $repo = $doctrine->getRepository(Espace::class);
        $espace = $repo->findAll();

        return $this->render('espaces/index.html.twig', [
            "espaces" => $espace,
            "formulaire" => $form->createView()
        ]);
    }

    #[Route('/espaces/supprimer/{id}', name: 'espaces_supprimer')]
    public function supprimerEspace($id, ManagerRegistry $doctrine, Request $request)
    {

        $espace = $doctrine->getRepository(Espace::class)->find($id);


        if (!$espace) {
            throw $this->createNotFoundException("Aucun espace avec l'id $id");
        }

        $form = $this->createForm(EspaceSupprimerType::class, $espace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $doctrine->getManager();

            $em->remove($espace);

            $em->flush();

            return $this->redirectToRoute("app_espaces");

        }

        return $this->render("espaces/supprimer.html.twig", [
            "espace" => $espace,
            "formulaire" => $form->createView()
        ]);


    }

    #[Route('/espaces/modifier/{id}', name: 'espaces_modifier')]
    public function modifierCategorie($id, ManagerRegistry $doctrine, Request $request)
    {
        $espace = $doctrine->getRepository(Espace::class)->find($id);

        if (!$espace) {
            throw $this->createNotFoundException("Aucune espace avec l'id $id");
        }

        $form = $this->createForm(EspaceType::class, $espace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if ((($form->getData()->getDateOuverture() !== null && $form->getData()->getDateFermeture() !== null) && $form->getData()->getDateOuverture() < $form->getData()->getDateFermeture())
                || ($form->getData()->getDateOuverture() === null && $form->getData()->getDateFermeture() === null)
            ) {


                $em = $doctrine->getManager();

                $em->persist($espace);

                $em->flush();

                return $this->redirectToRoute("app_espaces");

            } else {
                throw $this->createNotFoundException("Erreur dans le formulaire : vérifier si les dates d'ouverture et de fermeture sont correctement indiquées");
            }
        }


            return $this->render("espaces/modifier.html.twig", [
                "espace" => $espace,
                "formulaire" => $form->createView()
            ]);


        }
}

templates/espaces/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des espaces {% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Gestion des espaces</h1>
        <table class="table table-striped">
            <tr>
                <th>Nom de l'espace</th>
                <th>Superficie en m²</th>
                <th>Date d'ouverture</th>
                <th>Date de fermeture</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            {% for e in espaces %}
                <tr>
                    <td>{{ e.nom }}</td>
                    <td>{{ e.superficie }}</td>
                    <td>{% if e.dateOuverture %}
                            {{ e.dateOuverture.format('d/m/Y') }}
                            {% else %}
                            Aucune date
                        {% endif %}
                        </td>
                    <td>{% if e.dateFermeture %}
                            {{ e.dateFermeture.format('d/m/Y') }}
                        {% else %}
                            Aucune date
                        {% endif %}</td>
                    <td>
                        <a class="btn btn-primary" href="{{ path("espaces_modifier", {"id":e.id}) }}">modifier</a>
                    </td>
                    <td>
                        <a class="btn btn-danger" href="{{ path("espaces_supprimer", {"id":e.id}) }}">supprimer</a>
                    </td>
                    <td>
                        <a class="btn btn-success" href="{{ path("voir_enclos", {"id":e.id}) }}">voir les enclos</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

        <h2>Ajouter un espace</h2>
        {{ form(formulaire) }}


    </div>
{% endblock %}

templates/espaces/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Espace{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Modifier <i> {{ espace.nom }}</i></h1>

        {{ form(formulaire) }}

    </div>
{% endblock %}

templates/espaces/supprimer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer espace{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Voulez vous vraiment supprimer l'espace <i>{{ espace.nom }}</i> ?</h1>

        {{ form(formulaire) }}

    </div>
{% endblock %}

templates/espaces/voirEnclos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des enclos {% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Gestion des enclos de l'espace  {{ espace.nom }}</h1>
        <table class="table table-striped">
            <tr>
                <th>Nom de l'enclos</th>
                <th>Superficie en m²</th>
                <th>Nombre d'animaux maximum</th>
                <th>Quarentaine</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            {% for e in enclos %}
                <tr>
                    <td>{{ e.nom }}</td>
                    <td>{{ e.superficie }}</td>
                    <td>{{ e.maxAnimaux }}</td>
                    <td>{% if e.quarentaine == 1 %}
                            Oui
                        {% else %}
                            non
                        {% endif %}</td>
                    <td>
                         <a class="btn btn-primary" href="{{ path("enclos_modifier", {"id":e.id}) }}">modifier</a>
                    </td>
                    <td>
                         <a class="btn btn-danger" href="{{ path("enclos_supprimer", {"id":e.id}) }}">supprimer</a>
                    </td>
                    <td>
                         <a class="btn btn-success" href="{{ path("enclos_voirAnimaux", {"id":e.id}) }}">voir les animaux</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

        <h2>Ajouter un enclos</h2>
        <a class="btn btn-primary" href="{{ path("enclos_ajouter") }}">Ajouter un enclos</a>


    </div>
{% endblock %}